### ISSUE TITLE
[1.x] vulcanize failed with iron-icon.html

### ISSUE THREAD

**Issue by ragingwind** [Polymer/vulcanize#174]
I've got an error while I try to vulcanize a element.html which has imported `iron-icon`. It occurs during process `deduplicate comments`. It seems that the error is related to dom5.js but I'm not sure that. feel free to close. here is log message:

```
(.nvm/v0.10.29/lib/node_modules/vulcanize/node_modules/dom5/dom5.js:342:20)
    at Object.insertBefore (.nvm/v0.10.29/lib/node_modules/vulcanize/node_modules/dom5/dom5.js:351:3)
    at prepend (.nvm/v0.10.29/lib/node_modules/vulcanize/lib/vulcan.js:173:10)
    at .nvm/v0.10.29/lib/node_modules/vulcanize/lib/vulcan.js:141:5
    at Array.forEach (native)
    at flatten (.nvm/v0.10.29/lib/node_modules/vulcanize/lib/vulcan.js:136:19)
    at flatten (.nvm/v0.10.29/lib/node_modules/vulcanize/lib/vulcan.js:111:23)
    at .nvm/v0.10.29/lib/node_modules/vulcanize/lib/vulcan.js:255:19
    at lib$es6$promise$$internal$$tryCatch (.nvm/v0.10.29/lib/node_modules/vulcanize/node_modules/es6-promise/dist/es6-promise.js:319:16)
    at lib$es6$promise$$internal$$invokeCallback (.nvm/v0.10.29/lib/node_modules/vulcanize/node_modules/es6-promise/dist/es6-promise.js:331:17)

```

I'm using 0.9:
```
"polymer": "Polymer/polymer#v0.9.0-rc.1",
 "iron-elements": "PolymerElements/iron-elements#~0.9.0"
```

My element.html
```
<!doctype html>
<html>
<head>
  <link rel="import" href="../bower_components/iron-icon/iron-icon.html">
  <link rel="import" href="../bower_components/iron-iconset/iron-iconset.html">
</head>
</html>
```

**Comment by azakus** [comment]
The path should be `../bower_components/iron-icons/iron-icon.html`, note the plural *icons*. Took me a second to see that :).

**Comment by azakus** [comment]
Whoops, my paths were wrong. I see that message now.

**Comment by azakus** [comment]
Hmm, looks like a comment in iron-iconset is not being pulled from the `commentMap` correctly.
@garlicnation, `comments.keys` and `comments.get` may not be a stable transformation.

**Comment by azakus** [comment]
Fixed in 1.4.1

**Comment by rsORAU** [comment]
I am still experiencing an error when vulcanizing with an import of iron-icons.  I experience a similar issue with trying to vulcanize a file with the import paper-icon-button. I also tried using the stripComments and inlineCss: false options, but the issue persists. Also, the error when vulcanizing a file with imported iron-icons occurs in the '--layout-around-justified: {
 -ms-flex-pack: distribute;'

 Any ideas whether this could be related, or what could be happening.  Thank you in advanced.
