### ISSUE TITLE
gulp-vulcanize doesnt seem to make use of abspath option

### ISSUE THREAD

**Issue by gaarf** [Polymer/vulcanize#203]
_gulp-vulcanize_ does not seem to pick up the `abspath` option. It works fine when using _vulcanize_ directly on command line. 

```
gulp.task('vulcanize', ['html:elements'], function (done) {

  /**
   * gulp-vulcanize does not work as expected!
   */

  // return gulp.src('./dist/assets/elements/x-app/all-imports.html')
  //   .pipe(plug.vulcanize({
  //     abspath: __dirname
  //   }))
  //   .pipe(plug.concat('x-app.vulcanized.html'))
  //   .pipe(gulp.dest('./dist/assets/bundle'));


  /**
   * same thing using command-line does work
   */

  var output = [],
      child = spawn(
        './node_modules/gulp-vulcanize/node_modules/.bin/vulcanize',
        [ '--abspath', '.', 'dist/assets/elements/x-app/all-imports.html' ],
        { cwd: __dirname }
      );

  child.stdout.on('data', function (b) {
    output.push(b);
  });

  child.on('close', function() {
    var filename = __dirname + '/dist/assets/bundle/x-app.vulcanized.html';
    mkdirp(path.dirname(filename), function() {
      fs.writeFile(filename, Buffer.concat(output), done);
    });
  });

});
```

`all-imports.html` contains both relative and absolute imports. Eg:

```
<link rel="import" href="./x-app.html">
<link rel="import" href="/bower_components/paper-styles/paper-styles.html">
<link rel="import" href="../lorem-ipsum/lorem-ipsum.html">
```

**Comment by seahrh** [comment]
I have a similar issue on Win7; abspath is concatenated *twice*. gulp-vulcanize throws the following error:

    errno: 34
    code: ENOENT
    path: C:\path\to\dist\dir\path\to\dist\dir\index.html

I am vulcanizing in my dist directory (suggested in #51)

    gulp.task('vulcanize', function() {

        var DEST_DIR = bases.dist + 'WEB-INF/pages';

        return gulp.src('*.html', {
            cwd : DEST_DIR
        }).pipe($.vulcanize({
            abspath : bases.dist,
            inlineScripts : false,
            // inline css does not work if paper-input is imported
            inlineCss : false,
            stripComments : true
        })).on('error', error).pipe($.rename({
            extname : '.vul.html'
        })).pipe(gulp.dest(DEST_DIR));

    });

On vulcanize 1.9.1, gulp-vulcanize 6.0.1, Polymer 1.0.3.

**Comment by azakus** [comment]
Should be working with vulcanize 1.9.3. Please run `npm update`

**Comment by gaarf** [comment]
@azakus thanks, did the update, but didn't see any change at first. I was seeing same issue as @seahrh, double abspath.

Finally got it to work by changing `gulp.src('./dist/assets/elements/x-app/all-imports.html')` to `gulp.src('/dist/assets/elements/x-app/all-imports.html')` - just removing that `.` did the trick.

**Comment by seahrh** [comment]
Updated to vulcanize 1.9.3 but I am still seeing the same issue (double abspath). Having a leading / in gulp.src did not work for me.

**Comment by csmith932** [comment]
This issue is unresolved. Some clues for troubleshooting:

1) The relationship to gulp-vulcanize derives from the fact that gulp-vulcanize resolves file.path to the absolute file path.
2) If you run vulcanize with --inline-css, an absolute file path, and no/empty --abspath then it fails due to "no resolver found".
3) If you run vulcanize with an absolute file path and anything nontrivial for --abspath (with or without --inline-css) then it fails when trying to open an invalid file path composed of the concatenation of the --abspath value and the absolute input file path.
4) The "no resolver found" error appears to be associated with CSS files referencing external URLs of the form "//domain.com/etc" without a leading http or https. These should be handled in the solution to #182 but the constants.EXTERNAL_URL isn't picking up on it. "EXTERNAL_URL: /^(?:https?:)?\/\/|(?:\/\/)/" is a quickie workaround for that specific URL pattern but it isn't a permanent solution and only addresses part of the problem.

**Comment by azakus** [comment]
Yeah I think I understand the issue now.

There is no way to specify the path when using abspath in gulp because it read the file and forward it with its own metadata. One possible fix is to provide the input file path as an option, and ignore the path from gulp. In fact, this would probably be better anyway as it would allow for using the file buffer from gulp directly.

I'm confused by (4), this is explicitly tested for with https://github.com/Polymer/vulcanize/commit/47f684b5ba2428b442321b3372d29600e9774161

**Comment by seahrh** [comment]
Yes please reopen this issue. I also have the same `inline-css` "no resolver found" problem as what @csmith932 described in (2).

**Comment by makrolabs** [comment]
Same problem here on Windows x64

**Comment by azakus** [comment]
I've added a new option, `inputUrl`, that will override the file path gulp gives to vulcanize. This will fix instances on windows for single input files to be mapped to a URL for abspath usage correctly.

An example is here: https://github.com/Polymer/vulcanize/commit/11f9af762b42da6c0bbead9e2c92543564b82e47

**Comment by seahrh** [comment]
@azakus, only one file is vulcanized in your example. Is there a way I could vulcanize multiple files in my gulp task? 

    return gulp.src(['*.html', '!*' + VULCANIZED_EXT], { // many files
            cwd : 'src/main/webapp/WEB-INF/pages'
        }).pipe($.vulcanize({
            abspath : 'src/main/webapp',
            inputUrl : '/WEB-INF/pages/index.html', // one file
            inlineScripts : false,
            inlineCss : false,
            stripComments : true
        })).on('error', error).pipe($.rename({
            extname : VULCANIZED_EXT
        })).pipe(gulp.dest('src/main/webapp/WEB-INF/pages'));

**Comment by jimmidyson** [comment]
I still cannot get this to work with gulp-vulcanize properly - polymer is included twice. Output during build:

```
Ignoring duplicate element definition: custom-style
Ignoring duplicate element definition: dom-template
Ignoring duplicate element definition: dom-repeat
Ignoring duplicate element definition: array-selector
Ignoring duplicate element definition: dom-if
Ignoring duplicate element definition: dom-bind
```

And in browser when loading vulcanized elements:

```
Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.
```

If I try the `abspath` & `inputUrl` config like:

```
gulp.task('vulcanize', function () {
    var DEST_DIR = 'dist/elements';
  
    return gulp.src('dist/elements/elements.vulcanized.html')
      .pipe($.vulcanize({
        abspath: path.resolve('dist'),
        inputUrl: '/elements/elements.vulcanized.html',
        excludes: [
        ],
        stripExcludes: false,
        inlineScripts: false,
        inlineCss: false,
        implicitStrip: true,
        stripComments: true
      })) 
      .pipe($.crisper())
      .pipe(gulp.dest(DEST_DIR))
      .pipe($.size({title: 'vulcanize'}));
  });
```

The vulcanize task doesn't run, gulp just exits with no error.

Running `vulcanize -p dist /elements/elements.vulcanized.html` creates the correct content.

**Comment by hawkett** [comment]
I've also had this issue, and found the current solution is not to import polymer anywhere in my project. I suspect it is a known problem, because polymer-start-kit also doesn't import polymer anywhere in the project. It would seem the polymer dependency is resolved via the imported components that declare the polymer import (e.g. paper-toolbar), but it's not clear to me why they can declare the import, but I cannot (when vulcanizing).

**Comment by jimmidyson** [comment]
@hawkett Thanks for the tip but my project doesn't import polymer.html anywhere so this isn't the problem for me at least.

**Comment by jimmidyson** [comment]
So today this worked... must have been an old cached npm dependency.

**Comment by kubijo** [comment]
@jimmidyson Hi, I just came along to the same problem and I do not seem to have any import of polymer in my project files as well. Would you be able to expand as to what may helped you with fixing this?

**Comment by jimmidyson** [comment]
@kubijo iirc i cleaned out node_modules & bower_components, npm install, bower install & it all worked. Not sure why though...

**Comment by kubijo** [comment]
Well, tried that as well with no luck. Do you recall on which version you were ... meaning version of starter-pack and/or polymer?

**Comment by jimmidyson** [comment]
I'd just upgraded to starter pack 1.0.2 IIRC.

**Comment by kubijo** [comment]
Ok, I just 'resolved', so to any other confused wondering souls on the internet...

Apparently you can't have any imports **pointing to polymer.html** anywhere in your **.app/** - which means even those peer ones in eg. iron-input and *behavior elements.

Solution is to **move any import pointing to polymer.html to elements.html**. I find this, quite frankly, a terrible pattern since imports should be done in place of their usage and discarded if already imported elsewhere, but maybe there is a bigger picture here that I fail to see.

**Comment by jimmidyson** [comment]
That sounds like it's worth raising a separate issue for if one doesn't
already exist.

**Comment by dt-rush** [comment]
Has such an issue been opened yet? I'm experiencing a variant of this issue... there has to be some way to provide a path argument or have it detect the path so that it can resolve relative paths properly...

**Comment by kenkouot** [comment]
Still seeing this issue in https://github.com/sindresorhus/gulp-vulcanize with version 1.10.3 of vulcanize installed.
